FLAGS = -lcommons -pthread -lreadline

Planificador: Consola.o

Planificador.o: Planificador.h
	$(CC) -o Planificador.o Planificador.c $(FLAGS)

Consola.o: Consola.h
	$(CC) -o Consola.o Consola.c $(FLAGS)